# yaml-language-server: $schema=https://raw.githubusercontent.com/dbt-labs/dbt-jsonschema/main/schemas/dbt_project.json

name: santander_cycles
version: '1.0.0'
config-version: 2

profile: santander_cycles

model-paths: ["models"]
seed-paths:  ["seeds"]
test-paths:  ["tests"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  santander_cycles:
    staging:
      +schema:       staging
      +materialized: view
    marts:
      +schema:       mart
      +materialized: table

vars:
  project_id: "{{ env_var('GCP_PROJECT') }}"
  raw_dataset: "santander_cycles_raw"